# Generated by Django 5.1.1 on 2024-10-06 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id_estacionamiento', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('capacidad_total', models.IntegerField()),
                ('espacios_disponibles', models.IntegerField()),
                ('tarifa_hora', models.IntegerField()),
                ('horario_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('rut', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_user', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=11)),
                ('tipo_user', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id_espacio', models.AutoField(primary_key=True, serialize=False)),
                ('numero_espacio', models.CharField(max_length=10)),
                ('piso', models.IntegerField()),
                ('tipo_espacio', models.CharField(max_length=100)),
                ('ocupado', models.BooleanField(default=False)),
                ('sensor_id', models.IntegerField()),
                ('id_estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estacionamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('espacio_reservado', models.IntegerField()),
                ('hora_entrada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
                ('estado_reserva', models.CharField(max_length=100)),
                ('id_estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estacionamiento')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('monto_reserva', models.IntegerField()),
                ('fecha_pago', models.DateTimeField()),
                ('id_comprobante', models.CharField(max_length=50)),
                ('tipo_comprobante', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('estado_pago', models.CharField(max_length=50)),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo', to_field='placa'),
        ),
    ]
